import React from 'react';

export default function SignUpPage(props){
    //This can ONLY create users, admins will be manually entered.
    /* This should have inputs for:
        - Username
        - Password
        - Name

        It also has: 
        - "# of Reviews", but that should be set to 0 in db
        - "userID", but that should be generated by db*/

    return (
        <div>
            <form>
                <label htmlFor="name-input">Name:</label>
                <input type="text" id="name-input" name="name-input">
                    {/* This should be props.name */}
                </input>
                
                <label htmlFor="username-input">Username:</label>
                <input type="text" id="username-input" name="username-input">
                    {/* This should be props.username */}
                </input>
                

                <label htmlFor="password1-input">Password1:</label>
                <input type="password" id="password1-input" name="password1-input">
                    {/* This should be props.password1 */}
                </input>
                <label htmlFor="password2-input">Password2:</label>
                <input type="password" id="password2-input" name="password2-input">
                    {/* This should be blank */}
                </input>

                <button type="submit">Submit</button>
            </form>
        </div>
    );
}