import React from 'react';

export default function SignUpPage(props){
    //This can ONLY create users, admins will be manually entered.
    /* This should have inputs for:
        - Username
        - Password
        - Name

        It also has: 
        - "# of Reviews", but that should be set to 0 in db
        - "userID", but that should be generated by db*/

    return (
        <div>
            <form>
                {/* <label>Name:</label>
                <input>Name</input>
                
                <label>Username:</label>
                <input>Username</input> */}
                
                {/* For matching passwords */}
                {/* <label>Password1:</label>
                <input>Password1</input>
                <label>Password2:</label>
                <input>Password2</input> */}
                
                <button>Submit</button>
            </form>
        </div>
    );
}